CREATE OR REPLACE VIEW int_cell3g_bhi AS
select
rcid,
rfid,
ucid,
ts as ts,
interm_rnccn_bhrrcconnections(
rrcattconnestaborigconvcall,
rrcattconnestaborigstrmcal,
rrcattconnestaborigintactcall, 
rrcattconnestaborigbgrdcall, 
rrcattconnestaborigsubsccall, 
rrcattconnestabtermconvcall, 
rrcattconnestabtermstrmcall, 
rrcattconnestabtermintactcall, 
rrcattconnestabtermbgrdcall, 
rrcattconnestabemergency, 
rrcattconnestabiratcellresel, 
rrcattconnestabiratcco, 
rrcattconnestabregistration, 
rrcattconnestabdetach, 
rrcattconnestaborighighpriosig, 
rrcattconnestaboriglowpriosig, 
rrcattconnestabcallreestab, 
rrcattconnestabtermhighpriosig, 
rrcattconnestabtermlowpriosig, 
rrcattconnestabtermunknown, 
rrcattconnestabspare12) as rrc_bhi,
vsdedicateddownlinkkbytesrlcreferencecelldlrabcsspeech as speech_bhi,
vsdedicateddownlinkkbytesrlcreferencecelldlrabhsdpa as data_bhi,
interm_rnccn_bhcombined(
vsdedicateddownlinkkbytesrlcreferencecelldlrabhsdpa, 
vsdedicateddownlinkkbytesrlcreferencecelldlrabother, 
vsdedicateddownlinkkbytesrlcreferencecelldlrabcsspeech, 
vsdedicateddownlinkkbytesrlcreferencecelldlrabcsdata64, 
vsdedicateddownlinkkbytesrlcreferencecelldlrabcsstr, 
vsdedicateddownlinkkbytesrlcreferencecelldlrabhsdpa, 
vsdedicateddownlinkkbytesrlcreferencecelldlrabpsstr128, 
vsdedicateddownlinkkbytesrlcreferencecelldlrabpsstr256, 
vsdedicateddownlinkkbytesrlcreferencecelldlrabpsstr384, 
vsdedicateddownlinkkbytesrlcreferencecelldlrabpsstrother, 
vsdedicateddownlinkkbytesrlcreferencecelldlrabpsib8, 
vsdedicateddownlinkkbytesrlcreferencecelldlrabpsib16, 
vsdedicateddownlinkkbytesrlcreferencecelldlrabpsib32, 
vsdedicateddownlinkkbytesrlcreferencecelldlrabpsib64, 
vsdedicateddownlinkkbytesrlcreferencecelldlrabpsib128, 
vsdedicateddownlinkkbytesrlcreferencecelldlrabpsib256, 
vsdedicateddownlinkkbytesrlcreferencecelldlrabpsib384) as combined_bhi
from raw_rnccn_utrancell;