create view analysis_rncdxp as
select
rcid,ts,
sum(rrcattconnestaborigbgrdcall+rrcattconnestaborigintactcall
+rrcattconnestaborigstrmcal+rrcattconnestabtermbgrdcall
+rrcattconnestabtermintactcall+rrcattconnestabtermstrmcall
) as ps_attempts,
sum(vsdedicateddownlinkkbytesrlcreferencecelldlrabhsdpa+vsdedicateddownlinkkbytesrlcreferencecelldlrabpsib128
+vsdedicateddownlinkkbytesrlcreferencecelldlrabpsib16+vsdedicateddownlinkkbytesrlcreferencecelldlrabpsib256
+vsdedicateddownlinkkbytesrlcreferencecelldlrabpsib32+vsdedicateddownlinkkbytesrlcreferencecelldlrabpsib384
+vsdedicateddownlinkkbytesrlcreferencecelldlrabpsib64+vsdedicateddownlinkkbytesrlcreferencecelldlrabpsib8
+vsdedicateddownlinkkbytesrlcreferencecelldlrabpsstrother+vsdedicateduplinkkbytesrlcreferencecellulrabhsupa
+vsdedicateduplinkkbytesrlcreferencecellulrabpsib128) as ps_mbytes,
sum(rrcattconnestaborigconvcall+rrcattconnestabtermconvcall) as cs_attempts,
sum(vsrabmeancsvsumcum/36000) as cs_erlangs,
sum(rrcattconnestaboriglowpriosig+rrcattconnestabtermlowpriosig+rrcattconnestabtermunknown) as sms_attempts
from raw_rnccn_utrancell
group by rcid,ts
order by rcid,ts;