create view rncdxp as select
sum(rrcattconnestaborigbgrdcall+rrcattconnestaborigintactcall+rrcattconnestaborigstrmcal
+rrcattconnestabtermbgrdcall+rrcattconnestabtermintactcall+rrcattconnestabtermstrmcall) as ps_attempts,
sum(vsdedicateddownlinkkbytesrlcreferencecelldlrabhsdpa+vsdedicateddownlinkkbytesrlcreferencecelldlrabpsib128
+vsdedicateddownlinkkbytesrlcreferencecelldlrabpsib16+vsdedicateddownlinkkbytesrlcreferencecelldlrabpsib256
+vsdedicateddownlinkkbytesrlcreferencecelldlrabpsib32+vsdedicateddownlinkkbytesrlcreferencecelldlrabpsib384
+vsdedicateddownlinkkbytesrlcreferencecelldlrabpsib64+vsdedicateddownlinkkbytesrlcreferencecelldlrabpsib8
+vsdedicateddownlinkkbytesrlcreferencecelldlrabpsstrother+vsdedicateduplinkkbytesrlcreferencecellulrabhsupa
+vsdedicateduplinkkbytesrlcreferencecellulrabpsib128) as ps_mbytes
from raw_rnccn_utrancell


