create table report_iub_weeks_t (
 id varchar(8),
 w1_rls_req double precision,
 w1_rls_uns double precision,
 w1_rlr double precision,
 w1_ima_xl_mx double precision,
 w1_ima_xl_av double precision,
 w1_pcm_nb int,
 w2_rls_req double precision,
 w2_rls_uns double precision,
 w2_rlr double precision,
 w2_ima_xl_mx double precision,
 w2_ima_xl_av double precision,
 w2_pcm_nb int,
 w3_rls_req double precision,
 w3_rls_uns double precision,
 w3_rlr double precision,
 w3_ima_xl_mx double precision,
 w3_ima_xl_av double precision,
 w3_pcm_nb int,
 w4_rls_req double precision,
 w4_rls_uns double precision,
 w4_rlr double precision,
 w4_ima_xl_mx double precision,
 w4_ima_xl_av double precision,
 w4_pcm_nb int,
 constraint report_iub_weeks_t_pk primary key (id)
);